### PR TITLE
test case and proposed fix for numprops>1 query

### LINKED ISSUE #1196: salsah auto completion returns no or incomplete results
Our users complained about this and I think that it can be reproduced with `Anything`'s test data.

when looking at `Thing`s that are linked to other `Thing`, we find 14 results:

capture d ecran 2019-01-31 a 14 12 13

but when we count on the autocomplete to find them out, we find only 4 results:
capture d ecran 2019-01-31 a 14 11 41

### PR DESCRIPTION
**Pull request by loicjaouen**
fixes #1196

### CODE REVIEW

**Comment by loicjaouen** [comment]
in the above tests, we search for two queries, one with `numprops` the other without:

```
/v1/resources?restype_id=http%3A%2F%2Fwww.knora.org%2Fontology%2F0001%2Fanything%23Thing"&searchstr=***
/v1/resources?restype_id=http%3A%2F%2Fwww.knora.org%2Fontology%2F0001%2Fanything%23Thing"&searchstr=***&numprops=2
```

the first gives out the `Thing` with no properties:
```
      {
      "id": "http://rdfh.ch/0001/a-thing",
      "value": [
        "A thing"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/nVh9YJ1ZStSmCHb9hIdwWw",
      "value": [
        "excluded Charlie"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/thing_with_list_value",
      "value": [
        "A thing that has a list value"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/7uuGcnFcQJq08dMOralyCQ",
      "value": [
        "Hotel"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/tPfZeNMvRVujCQqbIbvO0A",
      "value": [
        "Echo"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/MiBwAFcxQZGHNL-WfgFAPQ",
      "value": [
        "Whiskey"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/WLSHxQUgTOmG1T0lBU2r5w",
      "value": [
        "Tango"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/9eSuQ_J7T0aOqoImTkwPxA",
      "value": [
        "excluded Bravo"
      ],
      "rights": 2
    }
  ```

the second the `Thing`s with some properties:
```
    {
      "id": "http://rdfh.ch/0001/qN1igiDRSAemBBktbRHn6g",
      "value": [
        "Something with a lot of markup",
        "Something with a lot of different markup. And more markup.\u001e"
      ],
      "rights": 1
    },
    {
      "id": "http://rdfh.ch/0001/a-thing-with-text-valuesLanguage",
      "value": [
        "ein verdammtes Ding mit einer Sprache",
        "Bonjour"
      ],
      "rights": 2
    },
    {
      "id": "http://rdfh.ch/0001/H6gBWUuJSuuO-CilHV8kQw",
      "value": [
        "testding",
        "test"
      ],
      "rights": 1
    },
    {
      "id": "http://rdfh.ch/0001/thing_with_richtext_with_markup",
      "value": [
        "test thing with markup",
        "This is a test that contains marked up elements. This is interesting text in italics. This is boring text in italics.\u001e"
      ],
      "rights": 2
    }
```

**Comment by loicjaouen** [comment]
i believe this is the right sparql request.  
Test fails because we also have to tell the scala code that `values` might be missing.

**Comment by loicjaouen** [comment]
note to myself: there is also the standard (non graphdb) case

**Comment by loicjaouen** [comment]
@benjamingeer : dear Ben, would you mind having a look despite the fact that this is not ready for merging as I left debug and commented code statements?

**Comment by benjamingeer** [comment]
@loicjaouen Thanks, I'll be glad to look at this next week.

File: webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala [hunk 1]
```diff
@@ -1977,5 +1978,41 @@ class ResourcesV1R2RSpec extends R2RSpec {
             }
 
         }
-    }
+
+        */
+
+        private val search = "/v1/resources?restype_id=http%3A%2F%2Fwww.knora.org%2Fontology%2F0001%2Fanything%23Thing"
```
Comment (benjamingeer) [inline webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala]: This looks reasonable to me.

**Comment by loicjaouen** [comment]
hi @benjamingeer , I think it's ready for a review if you don't mind

**Comment by benjamingeer** [comment]
Thanks, will look at this tomorrow.

File: webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala [hunk 2]
```diff
@@ -1194,46 +1194,61 @@ class ResourcesResponderV1(responderData: ResponderData) extends Responder(respo
...
-                            // ?firstProp is sufficient: the client requested just one property per resource that was found
-                            ResourceSearchResultRowV1(
-                                id = row.rowMap("resourceIri"),
-                                value = Vector(firstProp),
-                                rights = permissionCode
-                            )
+                                    )
+                                }
+                                case None => {
+                                    log.info("more values were asked (numberOfProps > 1), but there were none to be found")
```
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala]: Please make this `log.debug`.

File: webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala [hunk 3]
```diff
@@ -238,6 +238,29 @@ class ResourcesV1R2RSpec extends R2RSpec {
     }
 
 
+    private val search = "/v1/resources?restype_id=http%3A%2F%2Fwww.knora.org%2Fontology%2F0001%2Fanything%23Thing"
+    private val filter = "&searchstr=***"
+
+    private def checkSearch(search: String) = {
```
Comment (benjamingeer) [inline webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala]: Since this function doesn't check all searches, just a couple of very specific ones, could you give it a more specific name?

File: webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala (hunk 2 above)
Comment (loicjaouen) [reply webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala]: of course! 
d0e69e4

File: webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala (hunk 3 above)
Comment (loicjaouen) [reply webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala]: tried to make it more explicit:
1bbc89c

**Comment by loicjaouen** [comment]
let's see if the tests pass, the loading of the data times out on my laptop!

**Comment by loicjaouen** [comment]
Thanks @benjamingeer  :)
