### PR TITLE
fix (webapi): Fix permission checking on link values

### LINKED ISSUE #366: Error when hovering over the info box of "has standoff link to"
When hovering over the info box 
infobox
  of a "has standoff link to", an error occurs:

hasstandofflinktoinfobox

This is because a `LinkValue` is queried but it (always) belongs to the system user (and not the user that created the reference or something like that):

linkvalue

So Knora says:

```
{

    "status": 3,
    "error": "org.knora.webapi.ForbiddenException: User http://data.knora.org/users/PSGbemdjZi4kQ6GHJVkLGF does not have permission to see value http://data.knora.org/-umMNyKDSKy7c5m67rbLow/values/_xvRS7epQjiigZIB8dGTbQ",
    "access": "NO_ACCESS"

}
```

I think we handle this as follows: if the user has the right to see the target resource, he can see the link, otherwise not.

### PR DESCRIPTION
**Pull request by benjamingeer**
Fixes #366.

The docs say:

> Link values created automatically for resource references in standoff are automatically visible to all users, as long as they have permission to see the source and target resources.

When the values responder loads a link value, it must:

* Check the link value's permissions using `PermissionUtilV1.getUserPermissionOnLinkValueV1WithValueProps`, which takes into account the special case of standoff links.
* Check that the user has permission to view the source and target resources.

### CODE REVIEW

File: webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala [hunk 1]
```diff
@@ -1399,11 +1466,20 @@ class ValuesResponderV1 extends ResponderV1 {
 
             response <- (storeManager ? SparqlSelectRequest(sparqlQuery)).mapTo[SparqlSelectResponse]
             rows: Seq[VariableResultsRow] = response.results.bindings
-        } yield sparqlQueryResults2LinkValueQueryResult(rows, userProfile)
+            maybeLinkValueQueryResult = sparqlQueryResults2LinkValueQueryResult(rows, userProfile)
```
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala]: If I understand correctly, `sparqlQueryResults2LinkValueQueryResult` calls `PermissionUtilV1.getUserPermissionOnLinkValueV1WithValueProps` which always returns view permissions for standoff links (those are owned by the system user).

And since `PermissionUtilV1.getUserPermissionOnLinkValueV1WithValueProps` was not called before the changes you made here, no permissions could be granted to any user on a standoff link.

Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala]: However, standoff links were always returned by the resources responder (the error occurred not before hoveing over the information symbol). How does the handling of standoff links done by values responder relate to the that  performed by resources responder?

**Comment by tobiasschweizer** [comment]
I know that you hate this question, but could you add a test for this (querying a LinkValue representing a standoff link)?

File: webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala (hunk 1 above)
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala]: The resources responder already calls the special `PermissionUtilV1` method to check permissions on link values when necessary, so permissions on standoff links are handled correctly there. So does the search responder. I had just forgotten to use that method in one place in the values responder (because I had forgotten that you could get a link value via the normal route for getting values, not just through the special route for getting link values). This shows that having a special method just to check permissions on link values is a bad design, because it's easy to forget to use it. But I'd rather get the release done than refactor this now. Let's design it better for API v2.

**Comment by benjamingeer** [comment]
Yes of course.

File: webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala (hunk 1 above)
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala]: Ok, that's fine. I agree that  we have to get V1 out before we do that refactoring.
