### PR TITLE
Reject link value properties in Gravsearch queries in the simple schema

### LINKED ISSUE #1138: Need better error checking when link value property used in Gravsearch
Example from https://github.com/nie-ine/nieOS/issues/139#issuecomment-451381355:

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX kuno-raeber: <http://0.0.0.0:3333/ontology/004D/kuno-raeber/simple/v2#>
PREFIX language: <http://0.0.0.0:3333/ontology/004F/language/simple/v2#>
PREFIX text-editing: <http://0.0.0.0:3333/ontology/005A/text-editing/simple/v2#>
        
        CONSTRUCT {
        
        ?transcription knora-api:isMainResource true .
        ?transcription language:hasContent ?content .
        ?transcription text-editing:isDiplomaticTranscriptionOfTextOnPageValue ?page .
        
        } WHERE {
        
        BIND(<http://rdfh.ch/004D/--9JRHpRTJCz7DwXz6Xqpg> AS ?transcription)
        ?transcription language:hasContent ?content .
        ?transcription text-editing:isDiplomaticTranscriptionOfTextOnPageValue ?page .
            
        } OFFSET 0
```

This produces the error:

```
{
    "error": "org.knora.webapi.NotFoundException: Some requested entities were not found: http://api.knora.org/ontology/knora-api/simple/v2#LinkValue"
}
```

This is because `text-editing:isDiplomaticTranscriptionOfTextOnPageValue` is a link value property, which is not allowed in Gravsearch. The error checking should reject the link value property.

### PR DESCRIPTION
**Pull request by benjamingeer**
If you try to use a link value property in a Gravsearch query in the simple schema, you get a confusing error message. This fix returns a better error message, saying that the property is not found.

Fixes #1138.

### CODE REVIEW

File: webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala [hunk 1]
```diff
@@ -7331,5 +7331,30 @@ class SearchRouteV2R2RSpec extends R2RSpec {
...
+                  |    ?book a incunabula:book .
+                  |    ?book incunabula:title ?title .
+                  |    ?page a incunabula:page .
+                  |    ?page incunabula:partOfValue ?book .
+                  |}
+                """.stripMargin
+
+            Post("/v2/searchextended", HttpEntity(SparqlQueryConstants.`application/sparql-query`, gravsearchQuery)) ~> addCredentials(BasicHttpCredentials(incunabulaUserEmail, password)) ~> searchPath ~> check {
+
+                assert(status == StatusCodes.NOT_FOUND, response.toString)
```
Comment (tobiasschweizer) [inline webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala]: What does the error message say now exactly? Does it say that the property `incunabula:partOfValue` was not found since it was added to `propertiesUnavailableInSchema`?

Would it make sense to check that the error message contains that information?

Comment (benjamingeer) [reply webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala]: It says:

```
Some requested entities were not found: http://0.0.0.0:3333/ontology/0803/incunabula/simple/v2#partOfValue
```

I added a check for the property IRI in the error message.

**Comment by benjamingeer** [comment]
@tobiasschweizer OK now?
