### PR TITLE
Fix performance problem at login

### LINKED ISSUE #290: Creation of session id on login
The way we create a session id that is sent to the user on login and used in the cookie header is  simple. Is there another feasible way? E.g. multiply with a random number?

`webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala`:
`val sId = System.currentTimeMillis().toString`

### LINKED ISSUE #443: Timeout at login
After having updated to the latest commit on `develop`, I sometimes have this problem logging in from the browser:

```
{"status":4,"error":"java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]"}

"NetworkError: 500 Internal Server Error - :3333/v1/session"
```

This does only happen sometimes right after having loaded all the data and started webapi. Could we increase the timeout? Maybe the new hashlib is slower than the old one?

```
[2017-03-01 15:47:40,782] ERROR - KnoraService(akka://webapi) - Unable to run route :3333/v1/session
webapi java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
webapi  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
webapi  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
webapi  at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
webapi  at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
webapi  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
webapi  at scala.concurrent.forkjoin.package$ForkJoinPool$.managedBlock(package.scala:22)
webapi  at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
webapi  at scala.concurrent.Await$.result(package.scala:123)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$getUserProfileByEmail(Authenticator.scala:480)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$authenticateCredentials(Authenticator.scala:298)
webapi  at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$extractCredentialsAndAuthenticate(Authenticator.scala:281)
webapi  at org.knora.webapi.routing.Authenticator.doLogin(Authenticator.scala:73)
webapi  at org.knora.webapi.routing.Authenticator.doLogin$(Authenticator.scala:71)
webapi  at org.knora.webapi.routing.v1.AuthenticateRouteV1$.doLogin(AuthenticateRouteV1.scala:33)
webapi  at org.knora.webapi.routing.v1.AuthenticateRouteV1$.$anonfun$knoraApiPath$8(AuthenticateRouteV1.scala:65)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi  at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi  at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
webapi  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
webapi  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi  at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:73)
webapi  at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1147)
webapi  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
webapi  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
webapi  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
webapi  at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
webapi  at akka.actor.Actor.aroundReceive(Actor.scala:484)
webapi  at akka.actor.Actor.aroundReceive$(Actor.scala:484)
webapi  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
webapi  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
webapi  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
webapi  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
webapi  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
webapi  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
webapi  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
webapi  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
webapi  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### PR DESCRIPTION
**Pull request by benjamingeer**
This fixes a performance problem caused by the use of `MessageUtil.toSource` in debugging output in `ProjectsResponderV1`. Also:

* Add a configuration option `app.triplestore.profile-queries` that outputs SPARQL queries and the amount of time they take.
* Change `ResourcesResponderV1SpecContextData` to load the expected book context response from a file in JSON format, rather than including it in the source code, to keep IntelliJ IDEA from running out of memory when compiling it. This makes it easier to run a profiler in IntelliJ.
* Use a UUID instead of the current time when generating a session ID in `Authenticator.authenticateCredentials()` (#290).
* Use `Future.sequence` instead of `Await.result` in `PermissionsResponderV1.permissionsDataGetV1()`.
* Use `Vector` and `Seq` instead of `List` in `PermissionsResponderV1`.
* Move functions for reading and writing text files out of `FakeTriplestore` and into a utility class, `FileUtil`.
* Reformat some code.

I'll document how to profile Knora in [VisualVM](https://visualvm.github.io/) using its [IntelliJ IDEA plugin](https://plugins.jetbrains.com/plugin/7115-visualvm-launcher) in another pull request.

Fixes #443.
Fixes #290.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
first login immediately after having reloaded the data is still slower, but faster than before.

timing

**Comment by benjamingeer** [comment]
Will this be good enough for your production server for now, or do we need to investigate further at the moment?

File: webapi/src/main/scala/org/knora/webapi/Main.scala [hunk 1]
```diff
@@ -29,15 +29,15 @@ object Main extends App with LiveCore with KnoraService  {
     //Kamon.start()
 
     /* Check and wait until all actors are running */
-    checkActorSystem
+    checkActorSystem()
```
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/Main.scala]: Did you do that because the method has side-effects? http://docs.scala-lang.org/style/method-invocation.html

File: webapi/src/main/scala/org/knora/webapi/Main.scala [hunk 2]
```diff
@@ -29,15 +29,15 @@ object Main extends App with LiveCore with KnoraService  {
...
 
     val arglist = args.toList
 
     if (arglist.contains("loadDemoData")) StartupFlags.loadDemoData send true
     if (arglist.contains("allowResetTriplestoreContentOperationOverHTTP")) StartupFlags.allowResetTriplestoreContentOperationOverHTTP send true
 
     /* Start the HTTP layer, allowing access */
-    startService
+    startService()
```
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/Main.scala]: see above

File: webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala [hunk 3]
```diff
@@ -67,77 +63,78 @@ class PermissionsResponderV1 extends ResponderV1 {
...
-            // find out to which project each group belongs to
-            //_ = log.debug("getPermissionsProfileV1 - find out to which project each group belongs to")
-            groups: List[(IRI, IRI)] <- Future(if (groupIris.nonEmpty) {
-                groupIris.map {
-                    groupIri => {
-                        val resFuture = for {
-                            groupInfo <- (responderManager ? GroupInfoByIRIGetRequest(groupIri, None)).mapTo[GroupInfoResponseV1]
-                            res = (groupInfo.group_info.belongsToProject, groupIri)
-                        } yield res
-                        Await.result(resFuture, 1.seconds)
```
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala]: Did that blocking `Await` have any effect slowing down the application?

File: webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala [hunk 4]
```diff
@@ -905,7 +890,9 @@ class ResourcesResponderV1Spec extends CoreSpec(ResourcesResponderV1Spec.config)
             actorUnderTest ! ResourceContextGetRequestV1(iri = "http://data.knora.org/c5058f3a", resinfo = true, userProfile = SharedAdminTestData.incunabulaProjectAdminUser)
 
             expectMsgPF(timeout) {
-                case response: ResourceContextResponseV1 => compareResourceCompoundContextResponses(received = response, expected = ResourcesResponderV1SpecContextData.expectedBookResourceContextResponse)
+                case response: ResourceContextResponseV1 =>
+                    val responseAsJson = response.toJsValue
+                    assert(responseAsJson == ResourcesResponderV1SpecContextData.expectedBookResourceContextResponse, "book context response did not match")
```
Comment (tobiasschweizer) [inline webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala]: If I understand correctly, the correct ordering of the dependent pages (according to their `seqnum`) is part of the query. So a 1:1 comparison is good.

I am just mentioning this because there are some tests in which the results have to be ordered according to the same pattern before they are compared (the ordering does not matter for the correctness of the results).

File: webapi/src/main/scala/org/knora/webapi/Main.scala (hunk 1 above)
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/Main.scala]: Yes.

File: webapi/src/main/scala/org/knora/webapi/Main.scala (hunk 2 above)
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/Main.scala]: Yes.

File: webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala (hunk 3 above)
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala]: Not as far as I could tell.

File: webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala (hunk 4 above)
Comment (benjamingeer) [inline webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala]: This test always assumed that the order was fixed.

**Comment by tobiasschweizer** [comment]
> Will this be good enough for your production server for now, or do we need to investigate further at the moment?

Do you have any idea what could explain that the first login takes about three times longer than any subsequent one? 
Also if a do a second login with another user, it is much faster than the first one.

File: webapi/src/main/scala/org/knora/webapi/Main.scala (hunk 1 above)
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/Main.scala]: IntelliJ pointed it out as a style recommendation.

File: webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala (hunk 4 above)
Comment (tobiasschweizer) [inline webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala]: Yes, that is absolutely correct. I justed wanted to make sure that this is what we want.

**Comment by benjamingeer** [comment]
I believe that the first login loads and caches data from the triplestore, which is reused in subsequent logins.

**Comment by tobiasschweizer** [comment]
> I believe that the first login loads and caches data from the triplestore, which is reused in subsequent logins.

Sounds reasonable. So why couldn't we load that data in the cache when die application is started?

**Comment by benjamingeer** [comment]
> So why couldn't we load that data in the cache when die application is started?

I guess we could. You'd have to ask @subotic, he wrote this code.

**Comment by tobiasschweizer** [comment]
Hey @subotic, could we cache data needed for authentication when webapi is started?

File: webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala (hunk 4 above)
Comment (benjamingeer) [inline webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala]: I guess so, since the SPARQL query has:

```
ORDER BY ?seqnum ?sourceObject ?isPreview
```

**Comment by benjamingeer** [comment]
In any case, I suspect that would require a non-trivial reworking of the code, so if we do it, it should be done in another pull request. Meanwhile, can we merge this one?

**Comment by tobiasschweizer** [comment]
could you make an issue for the caching so we do not forget? thx.

**Comment by benjamingeer** [comment]
Opened #468.

**Comment by subotic** [comment]
> Hey @subotic, could we cache data needed for authentication when webapi is started?

We probably could. This would require creating a `UserProfileV1` for each registered user and storing it into the cache. But I don't think that this will change anything. When a user is authenticated, then the same thing is executed for the first and any subsequent user.

**Comment by subotic** [comment]
I will move my last comment to the new issue.
