### PR TITLE
fix (webapi): CORS problems

### LINKED ISSUE #304: Error messages are swallowed
When making an unsuccessful request to the Knora API such as adding a duplicate value or violating the cardinality restrictions when creating a resource, the server sends back an unsuccessful HTTP status code, but no JSON describing the error.

```
HTTP/1.1 400 Bad Request
Server: akka-http/2.4.11
Date: Wed, 02 Nov 2016 16:43:31 GMT
Content-Type: application/json
Content-Length: 78
``` 

Even though the header indicates there is a JSON message, there is none.

### LINKED ISSUE #306: error on attempt to delete a value
When I want to delete a value, I get a CORS error:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3333/v1/values/http%3A%2F%2Fdata.knora.org%2Fx5zk7l6cSBm2poXqpl9nEw%2Fvalues%2FK2ZiIlj9SZe0sC9ImQ39NQ. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

cors

However, this could also be another problem that appears to be a CORS error for the browser. But there is no error message (see #304 ).

### PR DESCRIPTION
**Pull request by tobiasschweizer**
- Resolves #306: DELETE method was missing in CORS configuration
- Resolves #304: `Access-Control-Allow-Origin` is missing in response header and thus the browser blocks the answer (in responses with status code other than 200).

### CODE REVIEW

**Comment by subotic** [comment]
@github: Github has also some bugs. The last four changes where made by me (@subotic) and not @tobiasschweizer

**Comment by subotic** [comment]
This should work now. @tobiasschweizer could you please test it again with Salsah?

**Comment by tobiasschweizer** [comment]
I have a look at it right now.

File: webapi/src/main/scala/org/knora/webapi/KnoraService.scala [hunk 1]
```diff
@@ -93,16 +92,6 @@ trait KnoraService {
     private val systemUser = UserProfileV1(userData = UserDataV1(lang = "en"), isSystemUser = true)
 
     /**
-      * Brings the CORS rejection handler into scope
-      */
-    implicit def corsRejection = corsRejectionHandler
-
-    /**
-      * Bring the Knora exception handler into scope, which is responsible for converting our exceptions to HttpResponses
```
Comment (tobiasschweizer) [inline webapi/src/main/scala/org/knora/webapi/KnoraService.scala]: Bring**s**

**Comment by tobiasschweizer** [comment]
Nice job! Now I can delete resources and I get proper error messages on failed attempts to manipulate values.

**Comment by subotic** [comment]
Thanks :-) Can I merge?

**Comment by tobiasschweizer** [comment]
Yes, I think so. There is a small typo I found in the documentation you could fix before merging.

**Comment by subotic** [comment]
> There is a small typo I found in the documentation you could fix before merging.
The typo is in code that was deleted ;-)

**Comment by tobiasschweizer** [comment]
Still I want to fix it!

joking, sorry, my fault
