### PR TITLE
fix (webapi): admin fixes

### LINKED ISSUE #380: Knora 'Administration' docs - remarks and questions
Remarks
---------

- In **Permission Templates**, I can see no difference between the *OPEN* and *CLOSED* templates.

- In **Example Data stored in the permissions graph**, *Default object access permission on a ProjectMember' group*, the value of the M permission is wrong:
```
Default object access permission on a 'ProjectMember' group:
  <http://data.knora.org/permissions/[UUID]> rdf:type knora-base:DefaultObjectAccessPermission ;
       knora-base:forProject <http://data.knora.org/projects/images> ;
       knora-base:forGroup knora-base:ProjectMember ;
       knora-base:hasPermissions "CR knora-base:Creator|
                                   M <http://data.knora.org/permissions/[UUID]>|
                                   V knora-base:KnownUser"^^xsd:string .
```

- In **Example Data stored in the permissions graph**, *Administrative permissions on a 'ProjectMember' group*, `knora-base:hasPermission` is used for `knora-base:hasPermissions`
```
  <http://data.knora.org/permissions/[UUID]> rdf:type knora-base:AdministrativePermission ;
       knora-base:forProject <http://data.knora.org/projects/images> ;
       knora-base:forGroup knora-base:ProjectMember ;
       knora-base:hasPermission "ProjectResourceCreateAllPermission"^^xsd:string .
```

- I couldn't find `knora-base:hasPermissions` property neither in `knora-base.ttl` nor in `knora-admin.ttl`.

-  In *Example Project Information stored in admin named graph*, **Projects Endpoint**:
        `knora-base:projectOntolgyGraph` --> `knora-base:projectOntologyGraph`
      

Question
---------

- Given the following statement in **Administrative Permissions**

> The following permissions can be set via instances of ``knora-base:AdministrativePermission`` on any group belonging to a project. For users that are members of a number of groups with administrative permissions attached, the final set of permissions is additive and most permissive. The administrative permissions are stored in a compact format in a single string, which is the object of the predicate ``knora-base:hasPermissions`` attached to an instance of the ``knora-base:AdministrativePermission`` class. 

I am confused when I read this in **Projects Endpoint**:

> - create group named *ProjectAdmin*, give group *hasProjectAllAdminPermission* and *hasProjectResourceCreateAllPermission*
>       - create group named *ProjectMember*, give group *hasProjectResourceCreateAllPermission*,
>         *knora-base:hasDefaultChangeRightsPermission* for *knora-base:Creator*,
>         *knora-base:hasDefaultModifyPermission* for this *ProjectMember* group, and
> *knora-base:hasDefaultViewPermission* for *knora-base:KnownUser*

and the following examples from *Example Project Information stored in admin named graph*:
   ```
<http://data.knora.org/projects/[UUID]>
        rdf:type knora-base:knoraProject ;
        knora-base:projectBasepath "/imldata/SALSAH-TEST-01/images" ;
        knora-base:projectShortname "images" ;
        knora-base:projectLongname "Images Collection Demo" ;
        knora-base:projectOntolgyGraph "http://www.knora.org/ontology/images" ;
        knora-base:projectDataGraph "http://www.knora.org/data/images" ;
        knora-base:isActiveProject "true"^^xsd:boolean ;
        knora-base:hasSelfJoinEnabled "false"^^xsd:boolean .

   <http://data.knora.org/groups/[UUID]>
        rdf:type knora-base:UserGroup ;
        knora-base:groupName "ProjectAdmin" ;
        knora-base:groupDescription "Default Project Admin Group" ;
        knora-base:belongsToProject <http://data.knora.org/projects/[UUID]> ;
        knora-base:hasProjectAllAdminPermission "true"^^xsd:boolean ;
        knora-base:hasProjectResourceCreateAllPermission "true"^^xsd:boolean .

   <http://data.knora.org/groups/[UUID]>
        rdf:type knora-base:UserGroup ;
        knora-base:groupName "ProjectMember" ;
        knora-base:groupDescription "Default Project Member Group" ;
        knora-base:belongsToProject <http://data.knora.org/projects/[UUID]> ;
        knora-base:hasProjectResourceCreateAllPermission "true"^^xsd:boolean ;
        knora-base:hasDefaultChangeRightsPermission knora-base:Creator ;
        knora-base:hasDefaultViewPermission knora-base:KnownUser .
```
I would have expected
```
knora-base:hasProjectAllAdminPermission "true"^^xsd:boolean ;
knora-base:hasProjectResourceCreateAllPermission "true"^^xsd:boolean .
```
and 
```
knora-base:hasProjectResourceCreateAllPermission "true"^^xsd:boolean ;
knora-base:hasDefaultChangeRightsPermission knora-base:Creator ;
knora-base:hasDefaultViewPermission knora-base:KnownUser .
```
to be instances of `knora-base:AdministrativePermission` on groups. 

What am I missing/not understanding?

### LINKED ISSUE #408: Inconsistencies in permission checking when creating a value for a property from another project
I have 2 projects : 

1. ***drawings-gods***
In this project, permissions are not defined yet, apart from the fact that there is this **user**: 
```
<http://data.knora.org/users/drawings-gods-test-user1> a knora-base:User ;
        knora-base:userid "ddd"^^xsd:string ;  
        knora-base:givenName "ddd"^^xsd:string ;  
        knora-base:familyName "ddd"^^xsd:string ;  
        knora-base:password "********"^^xsd:string ;
        knora-base:email "ddd@d.ch"^^xsd:string ;
        knora-base:preferredLanguage "fr"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:isInProject <http://data.knora.org/projects/drawings-gods> ;
        knora-base:isInProjectAdminGroup <http://data.knora.org/projects/drawings-gods> ;
        knora-base:isInGroup <http://data.knora.org/groups/drawings-gods-snf-team> ;
        knora-base:isInSystemAdminGroup "false"^^xsd:boolean .`
```

2. ***parole-religieuse***
In this project, there is a **user**: 

```
<http://data.knora.org/users/parole-religieuse-test-user1> a knora-base:User ;
        knora-base:userid "parole"^^xsd:string ;
        knora-base:givenName "parole"^^xsd:string ;
        knora-base:familyName "parole"^^xsd:string ;
        knora-base:password "**********"^^xsd:string ;
        knora-base:email "parole@unil.ch"^^xsd:string ;
        knora-base:preferredLanguage "fr"^^xsd:string ;
        knora-base:status "true"^^xsd:boolean ;
        knora-base:isInProject <http://data.knora.org/projects/parole-religieuse> ; ;
        knora-base:isInProjectAdminGroup <http://data.knora.org/projects/parole-religieuse> ;
        knora-base:isInSystemAdminGroup "false"^^xsd:boolean .
```
a **ProjectMember** group is also defined with this `default object access permission` : 
```
### Default Object Access Permissions on ProjectMember Group
<http://data.knora.org/permissions/parole-religieuse-o1> rdf:type knora-base:DefaultObjectAccessPermission ;
                      knora-base:forProject <http://data.knora.org/projects/parole-religieuse> ;
                      knora-base:forGroup knora-base:ProjectMember ;
                      knora-base:hasPermissions "CR knora-base:ProjectAdmin|D knora-base:ProjectMember|M knora-base:KnownUser|RV knora-base:UnknownUser"^^xsd:string .
```

I am currently running some tests to have a better understanding of what the Modify permission means, compared to Delete, etc., for values, for resources. So I came to this use case : 

User from **parole-religieuse** creates a resource `Affilliation` in parole-religieuse project, and a value for the property `affiliationDate`  which has `owl:minCardinality "1"`. User log out.

User from **drawings-gods** project searches for `Affiliation` resources and tries to add a value to `affiliationDate`. He actually can do it. But as soon as he did, he gets the message : 
```
error
Forbidden
{"status":3,"error":"org.knora.webapi.ForbiddenException: User http://data.knora.org/users/drawings-gods-test-user1 does not have permission to see value http://data.knora.org/zWr6JcMXSPOwIRXFoI_8yw/values/QHVkD_rPSHaRUf_yotzY-A","access":"NO_ACCESS"}
```
And he can't actually see the value he just created, it is as if it didn't exist where as, when logged as a user from parole-religieuse project, I am able to see the value he just created.

--------
Here are some questions : 

**question 1**: is it was is intended from Modify permission? Is a user allowed to create a new value for a property but NOT a new instance of a resource ? 

**question 2**: given the `default object access permission` above, a `knora-based:KnownUser` should View all the ressources and all the values in parole-religieuse project. However, after drawings-gods user created values in parole-religieuse project, he is not allowed to see them. 

**question 3** : how is it possible that the same user (drawings-gods user) is finally allowed to View only *some* values for the same property? At the end, when a parole-religieuse user was able to View 6 dates, the drawings-gods user could only View the values he did not created and that was only 2 of them.

### PR DESCRIPTION
**Pull request by subotic**
### Issues

- resolves #380 
- resolves #408

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer @tobiasschweizer I have tried to make ``hasPermissions`` a required property, but there are a number of tests that fail because of triplestore inconsistency errors.

We can do this change in another pull request.

**Comment by benjamingeer** [comment]
> We can do this change in another pull request.

I think tests should pass before anything is merged to `develop`, so let's fix it here.

**Comment by benjamingeer** [comment]
Sorry, now I understand, I thought you were saying that the tests were failing on this branch. Yes, let's make the change in another pull request. I'll review this one tomorrow.

**Comment by subotic** [comment]
thanks :-)

File: webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala [hunk 1]
```diff
@@ -191,8 +191,12 @@ class PermissionsResponderV1 extends ResponderV1 {
 
         /* combines all permissions for each project and removes duplicate permissions inside a project  */
         val result: Future[Map[IRI, Set[PermissionV1]]] = for {
-            allPermission <- allPermissionsFuture
-            result = allPermission.groupBy(_._1).map { case (k, v) =>
+            allPermissions <- allPermissionsFuture
```
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala]: Please add a type annotation for `allPermissions`. Tuples are hard to read even without type annotations.

File: webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala [hunk 2]
```diff
@@ -191,8 +191,12 @@ class PermissionsResponderV1 extends ResponderV1 {
...
+
+            // remove instances with empty PermissionV1 sets
+            cleanedAllPermissions: Iterable[(IRI, Seq[PermissionV1])] = allPermissions.filter(_._2.nonEmpty)
+
+            result = cleanedAllPermissions.groupBy(_._1).map { case (k, v) =>
```
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala]: Please use descriptive variables instead of `k, v`.

File: webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala [hunk 3]
```diff
@@ -231,8 +236,12 @@ class PermissionsResponderV1 extends ResponderV1 {
...
         /* combines all permissions for each project and removes duplicate permissions inside a project  */
         val result: Future[Map[IRI, Set[PermissionV1]]] = for {
-            allPermission <- allPermissionsFuture
-            result = allPermission.groupBy(_._1).map { case (k, v) =>
+            allPermissions: Iterable[(IRI, Seq[PermissionV1])] <- allPermissionsFuture
+
+            // remove instances with empty PermissionV1 sets
+            cleanedAllPermissions: Iterable[(IRI, Seq[PermissionV1])] = allPermissions.filter(_._2.nonEmpty)
+
+            result = cleanedAllPermissions.groupBy(_._1).map { case (k, v) =>
```
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/responders/v1/PermissionsResponderV1.scala]: Please use descriptive variable names instead of `k, v`.

File: webapi/src/main/scala/org/knora/webapi/util/ActorUtil.scala [hunk 4]
```diff
@@ -92,8 +92,8 @@ object ActorUtil {
       * @param message the message that was received.
       * @param log    a [[LoggingAdapter]].
       */
-    def handleUnexpectedMessage(sender: ActorRef, message: Any, log: LoggingAdapter)(implicit executionContext: ExecutionContext): Unit = {
-        val unexpectedMessageException = UnexpectedMessageException(s"Unexpected message $message of type ${message.getClass.getCanonicalName}")
+    def handleUnexpectedMessage(sender: ActorRef, message: Any, log: LoggingAdapter, who: String = "")(implicit executionContext: ExecutionContext): Unit = {
+        val unexpectedMessageException = UnexpectedMessageException(s"$who received an unexpected message $message of type ${message.getClass.getCanonicalName}")
```
Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/util/ActorUtil.scala]: If `who == ""`, this error message won't make sense.

Instead, you could move this method to `ResponderV1`, and have it use `this.getClass.getName`.

File: webapi/src/main/scala/org/knora/webapi/messages/v1/responder/projectmessages/ProjectMessagesV1.scala [hunk 5]
```diff
@@ -75,12 +74,18 @@ sealed trait ProjectsResponderRequestV1 extends KnoraRequestV1
 
 // Requests
 /**
-  * Get all information about all projects.
+  * Get all information about all projects. The response is in for of [[ProjectsResponseV1]]
```
Comment (subotic) [inline webapi/src/main/scala/org/knora/webapi/messages/v1/responder/projectmessages/ProjectMessagesV1.scala]: No. If you could please look at the whole comment :-) There is a type there. I have just changed both comments to make it clearer:

For ProjectsGetRequestV1:
```
Get all information about all projects in form of [[ProjectsResponseV1]]
```

For ProjectsGetV1:
```
Get all information about all projects in form of a sequence of [[ProjectInfoV1]].


```

Comment (benjamingeer) [inline webapi/src/main/scala/org/knora/webapi/messages/v1/responder/projectmessages/ProjectMessagesV1.scala]: OK but why do we have both? They seem to return basically the same information.

Comment (subotic) [inline webapi/src/main/scala/org/knora/webapi/messages/v1/responder/projectmessages/ProjectMessagesV1.scala]: Their behavior and return type are different. The ``ProjectsGetRequestV1`` returns either something or a ``NotFound`` exception if there are no projects found. The ``ProjectsGetV1`` returns an empty sequence in those cases. Also ``ProjectsGetRequestV1`` will eventually check for the user's permissions for the request, but ``ProjectsGetV1`` will not. The one is used in a route the other internally. We have a few messages like this. They follow this convention:
 - SomethingSomethingRequestV1 -> Used in routes and have always a SomethingSomethingResponseV1 as a response.
 - SomethingSomethingV1 -> Used internally and can have basically anything as a response.

**Comment by benjamingeer** [comment]
> The ``ProjectsGetRequestV1`` returns either something or a ``NotFound`` exception if there are no projects found. The ``ProjectsGetV1`` returns an empty sequence in those cases. Also ``ProjectsGetRequestV1`` will eventually check for the user's permissions for the request, but ``ProjectsGetV1`` will not. 

OK, could you just add these details to the Scaladoc comments?

**Comment by subotic** [comment]
Comments added.

**Comment by benjamingeer** [comment]
Great, thanks, please merge!

**Comment by subotic** [comment]
thanks for the review :)
